version: "3.5"
services:
  www:
    image: thalasoft.com:5000/www.folkuniversitet
    ports:
      - "85:80"
      - "86:443"
    networks:
      folkuniversitet:
      common:
    volumes:
      - "~/dev/docker/projects/learnintouch/volumes/www.folkuniversitet/account/data:/usr/local/learnintouch/www/folkuniversitet/account/data"
      - "~/dev/docker/projects/learnintouch/volumes/engine:/usr/local/learnintouch/engine"
      - "~/dev/docker/projects/common/volumes/letsencrypt/certbot/conf/live/thalasoft.com:/usr/local/learnintouch/letsencrypt"
      - "~/dev/docker/projects/common/volumes/logs:/usr/local/apache/logs"
      - "~/dev/docker/projects/common/volumes/logs:/usr/local/learnintouch/logs"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      WWW_FOLKUNIVERSITET_DB_NAME: db_folkuniversitet
      WWW_FOLKUNIVERSITET_DB_USER: folkuniversitet
      WWW_FOLKUNIVERSITET_NAME: folkuniversitet
      WWW_FOLKUNIVERSITET_DOMAIN: folkuniversitet.thalasoft.com
      WWW_FOLKUNIVERSITET_SCHEME: https
      STAFF_EMAIL: mittiprovence@yahoo.se
      NODEJS_SOCKET_PORT: 9002
    secrets:
      - DB_ROOT_PASSWORD
      - LEARNINTOUCH_DB_NAME
      - LEARNINTOUCH_DB_USER
      - LEARNINTOUCH_DB_PASSWORD
      - WWW_FOLKUNIVERSITET_DB_PASSWORD
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 10s
    healthcheck:
      test: curl --fail http://127.0.0.1:80/engine/ping.php || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
  nodejs:
    image: thalasoft.com:5000/nodejs-learnintouch
    ports:
      - "9003:9001"
      - "9004:9002"
    networks:
      folkuniversitet:
      common:
    volumes:
      - "~/dev/docker/projects/learnintouch/volumes/engine:/usr/local/learnintouch/engine"
      - "~/dev/docker/projects/common/volumes/letsencrypt/certbot/conf/live/thalasoft.com:/usr/local/learnintouch/letsencrypt"
      - "~/dev/docker/projects/common/volumes/logs:/usr/local/learnintouch/logs"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 10s
    healthcheck:
      test: curl --fail http://127.0.0.1:9001/ping || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
networks:
  folkuniversitet:
    name: folkuniversitet
  common:
    external: true
    name: common
secrets:
  DB_ROOT_PASSWORD:
    external: true
  LEARNINTOUCH_DB_NAME:
    external: true
  LEARNINTOUCH_DB_USER:
    external: true
  LEARNINTOUCH_DB_PASSWORD:
    external: true
  WWW_FOLKUNIVERSITET_DB_PASSWORD:
    external: true

