version: "3.7"
services:
  fhs:
    image: localhost:5000/www.fhs-install
    networks:
      learnintouch:
      common:
    volumes:
      - "~/dev/docker/projects/common/volumes/database/mariadb/data:/usr/local/mariadb/install/data"
      - "~/dev/docker/projects/learnintouch/volumes/www.fhs/account/backup:/usr/local/learnintouch/www/fhs.europasprak.com/account/backup"
      - "~/dev/docker/projects/learnintouch/volumes/www.fhs/account/data:/usr/local/learnintouch/www/fhs.europasprak.com/account/data"
    user: "${CURRENT_UID}:${CURRENT_GID}"
    environment:
      HOST_USER_ID: ${CURRENT_UID}
      HOST_GROUP_ID: ${CURRENT_GID}      
    secrets:
      - DB_ROOT_PASSWORD      
      - WWW_FHS_DB_PASSWORD
    deploy:
      replicas: 1
      restart_policy:
        condition: none
networks:
  learnintouch:
    name: learnintouch
  common:
    external: true
    name: common
secrets:
  DB_ROOT_PASSWORD:
    external: true  
  WWW_FHS_DB_PASSWORD:
    external: true    
