version: "3.1"
services:
  learnintouch:
    image: thalasoft.com:5000/learnintouch
    environment:
      HOST_USER_ID: ${CURRENT_UID}
      HOST_GROUP_ID: ${CURRENT_GID}      
    secrets:
      - DB_ROOT_PASSWORD      
      - LEARNINTOUCH_DB_NAME
      - LEARNINTOUCH_DB_USER
      - LEARNINTOUCH_DB_PASSWORD        
    volumes:
      - "~/dev/docker/projects/learnintouch/volumes/database/data:/usr/bin/mariadb/install/data"
    deploy:
      replicas: 1
      restart_policy:
        condition: none
  mysql:
    image: thalasoft.com:5000/mariadb:10.1.24
    volumes:
      - "~/dev/docker/projects/learnintouch/volumes/database/data:/usr/bin/mariadb/install/data"
      - "~/dev/docker/projects/learnintouch/volumes/logs:/usr/bin/mariadb/install/logs"
    environment:
      HOST_USER_ID: ${CURRENT_UID}
      HOST_GROUP_ID: ${CURRENT_GID}
    secrets:
      - DB_ROOT_PASSWORD      
secrets:
  DB_ROOT_PASSWORD:
    external: true  
  LEARNINTOUCH_DB_NAME:
    external: true
  LEARNINTOUCH_DB_USER:
    external: true
  LEARNINTOUCH_DB_PASSWORD:
    external: true
