version: "3"
services:
  learnintouch:
    image: thalasoft.com:5000/learnintouch
    container_name: learnintouch
    links:
      - mysql
  mysql:
    image: thalasoft.com:5000/mariadb:10.1.24
    container_name: mysql  
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "~/dev/docker/projects/learnintouch/volumes/database/data:/usr/bin/mysql/install/data"
      - "~/dev/docker/projects/learnintouch/volumes/logs:/usr/bin/mariadb/install/logs"
