version: "3.7"
services:
  learnintouch:
    image: localhost:5000/www.learnintouch-install
    networks:
      learnintouch:
      common:
    volumes:
      - "~/dev/docker/projects/common/volumes/database/data:/usr/local/mariadb/install/data"
    environment:
      HOST_USER_ID: ${CURRENT_UID}
      HOST_GROUP_ID: ${CURRENT_GID}      
    secrets:
      - DB_ROOT_PASSWORD      
      - WWW_LEARNINTOUCH_DB_PASSWORD        
    deploy:
      replicas: 1
      restart_policy:
        condition: none
networks:
  learnintouch:
    name: learnintouch
  common:
    external: true
    name: common
secrets:
  DB_ROOT_PASSWORD:
    external: true  
  WWW_LEARNINTOUCH_DB_PASSWORD:
    external: true    
