version: "3"
services:
  learnintouch-startup:
    image: localhost:5000/learnintouch-startup
    ports:
      - "81:80"
    networks:
      - learnintouch      
    volumes:
      - "~/dev/docker/projects/learnintouch/volumes/www.learnintouch/account/data:/usr/bin/learnintouch/www/learnintouch.com/account/data"
      - "~/dev/docker/projects/learnintouch/volumes/www.thalasoft/account/data:/usr/bin/learnintouch/www/thalasoft.com/account/data"
      - "~/dev/docker/projects/learnintouch/volumes/www.folkuniversitet/account/data:/usr/bin/learnintouch/www/folkuniversitet/account/data"
      - "~/dev/docker/projects/learnintouch/volumes/engine:/usr/bin/learnintouch/engine"
      - "~/dev/docker/projects/learnintouch/volumes/logs:/usr/bin/apache/logs"
      - "~/dev/docker/projects/learnintouch/volumes/logs:/usr/bin/learnintouch/logs"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3 
        window: 10s
    healthcheck:
      test: curl --fail http://127.0.0.1:80/engine/ping.php || exit 1
      interval: 5s
      timeout: 10s
      retries: 3  
  nodejs-learnintouch:
    image: localhost:5000/nodejs-learnintouch
    ports:
      - "9001:9001"
    networks:
      - learnintouch      
    volumes:
      - "~/dev/docker/projects/learnintouch/volumes/engine:/usr/bin/learnintouch/engine"
      - "~/dev/docker/projects/learnintouch/volumes/logs:/usr/bin/learnintouch/logs"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3 
        window: 10s
    healthcheck:
      test: curl --fail http://127.0.0.1:9001/ping || exit 1
      interval: 5s
      timeout: 10s
      retries: 3  
  mysql:
    image: localhost:5000/mariadb:10.1.24
    networks:
      - learnintouch      
    volumes:
      - "~/dev/docker/projects/learnintouch/volumes/database/data:/usr/bin/mariadb/install/data"
      - "~/dev/docker/projects/learnintouch/volumes/logs:/usr/bin/mariadb/install/logs"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3 
        window: 10s
    healthcheck:
      test: /usr/bin/learnintouch/db-health-check.sh
      interval: 5s
      timeout: 10s
      retries: 3  
  redis:
    image: localhost:5000/redis:3.0.7
    networks:
      - learnintouch      
    volumes:
      - "~/dev/docker/projects/learnintouch/volumes/logs:/usr/bin/redis/install/var/logs"
  logrotate:
    image: localhost:5000/logrotate
    networks:
      - learnintouch      
    volumes:
      - "~/dev/docker/projects/learnintouch/volumes/logs:/usr/bin/logrotate/logs"
networks:
  learnintouch:  
