version: "3.1"
services:
  folkuniversitet:
    image: localhost:5000/www.folkuniversitet
  mysql:
    image: localhost:5000/mariadb:10.1.24
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "~/dev/docker/projects/learnintouch/volumes/database/data:/usr/bin/mariadb/install/data"
      - "~/dev/docker/projects/learnintouch/volumes/logs:/usr/bin/mariadb/install/logs"
