version: "3"
services:
  www.folkuniversitet:
    image: thalasoft.com:5000/www.folkuniversitet
    container_name: www.folkuniversitet
    links:
      - mysql
  mysql:
    image: thalasoft.com:5000/mariadb:10.1.24
    container_name: mysql  
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "~/dev/docker/projects/learnintouch/volumes/database/data:/usr/bin/mariadb/install/data"
      - "~/dev/docker/projects/learnintouch/volumes/logs:/usr/bin/mariadb/install/logs"
