version: "3.9"
services:
  www:
    image: localhost:5000/www.learnintouch
    networks:
      common:
    volumes:
      - "~/dev/docker/projects/learnintouch/volumes/www.learnintouch/account/data:/usr/local/learnintouch/www/learnintouch.com/account/data"
      - "~/dev/docker/projects/learnintouch/volumes/www.learnintouch/account/backup:/usr/local/learnintouch/www/learnintouch.com/account/backup"
      - "~/dev/docker/projects/common/volumes/letsencrypt/certbot/conf/live/thalasoft.com:/usr/local/learnintouch/letsencrypt"
      - "~/dev/docker/projects/learnintouch/volumes/engine:/usr/local/learnintouch/engine"
      - "~/dev/docker/projects/common/volumes/logs:/usr/local/apache/logs"
      - "~/dev/docker/projects/common/volumes/logs:/usr/local/learnintouch/logs"
    user: "${CURRENT_UID}:${CURRENT_GID}"
    environment:
      HOST_USER_ID: ${CURRENT_UID}
      HOST_GROUP_ID: ${CURRENT_GID}
      DB_HOST: mysql
      DB_PORT: 3306
      WWW_LEARNINTOUCH_DB_NAME: db_learnintouch
      WWW_LEARNINTOUCH_DB_USER: learnintouch
      WWW_LEARNINTOUCH_NAME: learnintouch
      WWW_LEARNINTOUCH_DOMAIN: dev.learnintouch.com
      WWW_LEARNINTOUCH_SCHEME: http
      STAFF_EMAIL: mittiprovence@yahoo.se
      NODEJS_SOCKET_PORT: 9001
    secrets:
      - DB_ROOT_PASSWORD
      - LEARNINTOUCH_DB_NAME
      - LEARNINTOUCH_DB_USER
      - LEARNINTOUCH_DB_PASSWORD
      - WWW_LEARNINTOUCH_DB_PASSWORD
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 30s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.www.rule=Host(`dev.learnintouch.com`)"
        - "traefik.http.routers.www.entrypoints=web"
#        - "traefik.http.routers.www.entrypoints=websecure"
        - "traefik.http.services.www.loadbalancer.server.port=80"
#        - "traefik.http.services.www.loadbalancer.passhostheader=true" TODO What is this for ?
        # Doing a healthcheck
#        - "traefik.http.services.www.loadbalancer.healthcheck.path=/engine/ping.php"
#        - "traefik.http.services.www.loadbalancer.healthcheck.interval=10s"
#        - "traefik.http.services.www.loadbalancer.healthcheck.timeout=3s"
#        - "traefik.http.services.www.loadbalancer.healthcheck.scheme=http"
    healthcheck:
      test: curl --fail http://127.0.0.1:80/engine/ping.php || exit 1
      interval: 15s
      timeout: 3s
      retries: 3
  nodejs:
    image: localhost:5000/nodejs-learnintouch
    ports:
      - "9001:9001"
      - "9002:9002"
    networks:
      common:
    volumes:
      - "~/dev/docker/projects/learnintouch/volumes/engine:/usr/local/learnintouch/engine"
      - "~/dev/docker/projects/common/volumes/letsencrypt/certbot/conf/live/thalasoft.com:/usr/local/learnintouch/letsencrypt"
      - "~/dev/docker/projects/common/volumes/logs:/usr/local/learnintouch/logs"
    user: "${CURRENT_UID}:${CURRENT_GID}"
    environment:
      HOST_USER_ID: ${CURRENT_UID}
      HOST_GROUP_ID: ${CURRENT_GID}
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 30s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nodejs.rule=Host(`dev.learnintouch.com`)"
        - "traefik.http.routers.nodejs.entrypoints=web"
#        - "traefik.http.routers.nodejs.entrypoints=websecure"
        - "traefik.http.services.nodejs.loadbalancer.server.port=9001"
        # Doing a healthcheck
#        - "traefik.http.services.nodejs.loadbalancer.healthcheck.path=/ping"
#        - "traefik.http.services.nodejs.loadbalancer.healthcheck.interval=10s"
#        - "traefik.http.services.nodejs.loadbalancer.healthcheck.timeout=3s"
#        - "traefik.http.services.nodejs.loadbalancer.healthcheck.scheme=http"
    healthcheck:
      test: curl --fail http://127.0.0.1:9001/ping || exit 1
      interval: 15s
      timeout: 2s
      retries: 3
networks:
  common:
    name: common
    driver: overlay
    external: true
secrets:
  DB_ROOT_PASSWORD:
    external: true
  LEARNINTOUCH_DB_NAME:
    external: true
  LEARNINTOUCH_DB_USER:
    external: true
  LEARNINTOUCH_DB_PASSWORD:
    external: true
  WWW_LEARNINTOUCH_DB_PASSWORD:
    external: true
