version: "3.7"
services:
  folkuniversitet:
    image: localhost:5000/www.folkuniversitet-install
    networks:
      learnintouch:
      common:
    volumes:
      - "~/dev/docker/projects/common/volumes/database/mariadb/data:/usr/local/mariadb/install/data"
      - "~/dev/docker/projects/learnintouch/volumes/www.europasprak/account/backup:/usr/local/learnintouch/www/folkuniversitet.europasprak.com/account/backup"
      - "~/dev/docker/projects/learnintouch/volumes/www.europasprak/account/data:/usr/local/learnintouch/www/folkuniversitet.europasprak.com/account/data"
    environment:
      HOST_USER_ID: ${CURRENT_UID}
      HOST_GROUP_ID: ${CURRENT_GID}      
    secrets:
      - DB_ROOT_PASSWORD       
      - WWW_FOLKUNIVERSITET_DB_PASSWORD       
    deploy:
      replicas: 1
      restart_policy:
        condition: none
networks:
  learnintouch:
    name: learnintouch
  common:
    external: true
    name: common
secrets:
  DB_ROOT_PASSWORD:
    external: true
  WWW_FOLKUNIVERSITET_DB_PASSWORD:
    external: true

